-- db2a-student_club_v1
--
-- SQL source of db/db2a-student_club_v1.db, generated by tools/dump-schema.py.
-- Rebuild the database with:
--     sqlite3 db/db2a-student_club_v1.db < schema/db2a-student_club_v1.sql
-- Then check it with:
--     python3 tools/check-db.py

BEGIN TRANSACTION;
CREATE TABLE Clubs (
	CID CHAR(4) NOT NULL PRIMARY KEY, 
	Name CHAR(30) UNIQUE, 
    Teacher CHAR(100)
);
INSERT INTO "Clubs" VALUES('ASTR','Astronomy Club','Mr. Wong');
INSERT INTO "Clubs" VALUES('CHSS','Chess Club','Ms. Chan');
INSERT INTO "Clubs" VALUES('MATH','Mathematics Club','Mr. Lee');
INSERT INTO "Clubs" VALUES('COMP','Computer Club','Ms. Lau');
CREATE TABLE Students (
	SID CHAR(4) NOT NULL PRIMARY KEY, 
	Cls CHAR(2), 
	Clsno INT DEFAULT 1 CHECK (Clsno>=1 AND Clsno<=40), 
	Ename CHAR(30) NOT NULL, 
    ClubID CHAR(4) REFERENCES Clubs(CID)
);
INSERT INTO "Students" VALUES('0011','1A',1,'Alice','CHSS');
INSERT INTO "Students" VALUES('1021','1A',2,'Bob','ASTR');
INSERT INTO "Students" VALUES('0223','1A',3,'Cathy','CHSS');
INSERT INTO "Students" VALUES('0324','1A',4,'David','MATH');
INSERT INTO "Students" VALUES('9324','1B',1,'Emily',NULL);
CREATE INDEX student_name_index
  ON Students (Ename);
COMMIT;
