-- db2c-student_club_v3
--
-- SQL source of db/db2c-student_club_v3.db, generated by tools/dump-schema.py.
-- Rebuild the database with:
--     sqlite3 db/db2c-student_club_v3.db < schema/db2c-student_club_v3.sql
-- Then check it with:
--     python3 tools/check-db.py

BEGIN TRANSACTION;
CREATE TABLE Club (
  CID CHAR,
  Cname CHAR,
  PRIMARY KEY (CID)
);
INSERT INTO "Club" VALUES('ASTR','Astronomy Club');
INSERT INTO "Club" VALUES('CHSS','Chess Club');
INSERT INTO "Club" VALUES('MATH','Math Club');
INSERT INTO "Club" VALUES('COMP','Computer Club');
CREATE TABLE ClubInfo (
  CID CHAR,
  Syear INT,
  Teacher CHAR,
  PRIMARY KEY (CID, Syear),
  FOREIGN KEY (CID) REFERENCES Club(CID)
);
INSERT INTO "ClubInfo" VALUES('ASTR',2023,'Wong');
INSERT INTO "ClubInfo" VALUES('CHSS',2023,'Chan');
INSERT INTO "ClubInfo" VALUES('MATH',2023,'Lee');
INSERT INTO "ClubInfo" VALUES('COMP',2024,'Lau');
INSERT INTO "ClubInfo" VALUES('ASTR',2024,'Wong');
INSERT INTO "ClubInfo" VALUES('MATH',2024,'Kim');
CREATE TABLE ClubReg (
  CID CHAR,
  Syear INT,
  SID CHAR,
  PRIMARY KEY (CID, Syear, SID),
  FOREIGN KEY (SID) REFERENCES Student(SID),
  FOREIGN KEY (CID, Syear)
    REFERENCES ClubInfo(CID, Syear)
);
INSERT INTO "ClubReg" VALUES('ASTR',2023,'1021');
INSERT INTO "ClubReg" VALUES('CHSS',2023,'1021');
INSERT INTO "ClubReg" VALUES('MATH',2023,'0223');
INSERT INTO "ClubReg" VALUES('COMP',2024,'0324');
INSERT INTO "ClubReg" VALUES('MATH',2024,'0223');
INSERT INTO "ClubReg" VALUES('MATH',2024,'1021');
INSERT INTO "ClubReg" VALUES('ASTR',2024,'0324');
CREATE TABLE Student (
  SID CHAR,
  Sname CHAR,
  Phone CHAR,
  PRIMARY KEY (SID)
);
INSERT INTO "Student" VALUES('1021','Alice','61231236');
INSERT INTO "Student" VALUES('0223','Kathy','93030123');
INSERT INTO "Student" VALUES('0324','Emily','53698741');
CREATE VIEW ClubRecord AS
  SELECT ClubReg.CID,
         Club.Cname,
         ClubReg.Syear,
         ClubInfo.Teacher,
         ClubReg.SID,
         Student.Sname,
         Student.Phone
  FROM ClubReg
  INNER JOIN Student
     ON Student.SID = ClubReg.SID
  INNER JOIN ClubInfo
     ON ClubInfo.CID = ClubReg.CID
    AND ClubInfo.Syear = ClubReg.Syear
  INNER JOIN Club
     ON Club.CID = ClubInfo.CID;
COMMIT;
