-- db3_stationery_shop
--
-- SQL source of db/db3_stationery_shop.db, generated by tools/dump-schema.py.
-- Rebuild the database with:
--     sqlite3 db/db3_stationery_shop.db < schema/db3_stationery_shop.sql
-- Then check it with:
--     python3 tools/check-db.py

BEGIN TRANSACTION;
CREATE TABLE Category (Category_ID INTEGER PRIMARY KEY ON CONFLICT FAIL, Category_Name CHAR (20) NOT NULL ON CONFLICT ROLLBACK);
INSERT INTO "Category" VALUES(1,'Notebooks');
INSERT INTO "Category" VALUES(2,'Writing Instruments');
INSERT INTO "Category" VALUES(3,'Art Supplies');
CREATE TABLE Customer (Customer_ID CHAR (4) PRIMARY KEY ON CONFLICT FAIL, First_Name CHAR (40), Last_Name CHAR (20) NOT NULL ON CONFLICT ROLLBACK, Email CHAR (50) NOT NULL ON CONFLICT ROLLBACK, Phone_Number CHAR (15) NOT NULL ON CONFLICT ROLLBACK, Address CHAR (200) NOT NULL ON CONFLICT ROLLBACK);
INSERT INTO "Customer" VALUES('0001','John','Doe','john.doe@example.com','34567890','123 Main St, City');
INSERT INTO "Customer" VALUES('0002','Jane','Smith','jane.smith@example.com','98765432','456 Oak Ave, City');
INSERT INTO "Customer" VALUES('0003','Emily','Brown','emily.brown@example.com','55555555','789 Pine St, City');
INSERT INTO "Customer" VALUES('1004','David','Lee','david.lee@example.com','11111111','101 Maple Dr, City');
INSERT INTO "Customer" VALUES('1005','Olivia','Taylor','olivia.taylor@example.com','22222222','202 Birch Ln, City');
INSERT INTO "Customer" VALUES('2106','Noah','Carter','noah.carter@example.com','33333333','303 Cedar Rd, City');
INSERT INTO "Customer" VALUES('2207','Emma','Johnson','emma.johnson@example.com','44444444','404 Chestnut Ct, City');
INSERT INTO "Customer" VALUES('2418','Liam','Williams','liam.williams@example.com','55555555','505 Cypress Ave, City');
INSERT INTO "Customer" VALUES('2519','Ava','Jones','ava.jones@example.com','66666666','606 Douglas Blvd, City');
INSERT INTO "Customer" VALUES('2610','Sophia','Miller','sophia.miller@example.com','77777777','707 Elm St, City');
CREATE TABLE Order_Item (Order_Item_ID CHAR (10) PRIMARY KEY ON CONFLICT FAIL, Order_ID CHAR (12) REFERENCES Orders (Order_ID) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL", Product_ID CHAR (8) REFERENCES Product (Product_ID) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL", Quantity INTEGER DEFAULT 0, Selling_Price REAL);
INSERT INTO "Order_Item" VALUES('1','20231001-001','K001',2,5.0);
INSERT INTO "Order_Item" VALUES('2','20231001-001','K002',1,1.5);
INSERT INTO "Order_Item" VALUES('3','20231115-002','K003',1,2.0);
INSERT INTO "Order_Item" VALUES('4','20231115-002','K004',2,0.5);
INSERT INTO "Order_Item" VALUES('5','20231225-003','K005',3,1.0);
INSERT INTO "Order_Item" VALUES('6','20231225-003','K006',2,2.5);
INSERT INTO "Order_Item" VALUES('7','20240110-004','K007',1,5.0);
INSERT INTO "Order_Item" VALUES('8','20240110-004','K008',2,3.0);
INSERT INTO "Order_Item" VALUES('9','20240220-005','K009',4,3.0);
INSERT INTO "Order_Item" VALUES('10','20240220-005','K000',1,4.0);
CREATE TABLE Orders (Order_ID CHAR (8) PRIMARY KEY ON CONFLICT FAIL, Customer_ID CHAR (4) REFERENCES Customer (Customer_ID) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL", Order_Date DATE NOT NULL ON CONFLICT ROLLBACK, Total_Amount REAL DEFAULT 0, Status CHAR (10));
INSERT INTO "Orders" VALUES('20231001-001','2106','2023-10-01',10.0,'Shipped');
INSERT INTO "Orders" VALUES('20231115-002','2207','2023-11-15',5.0,'Delivered');
INSERT INTO "Orders" VALUES('20231225-003','1004','2023-12-25',20.0,'Pending');
INSERT INTO "Orders" VALUES('20240110-004','0003','2024-01-10',15.0,'Shipped');
INSERT INTO "Orders" VALUES('20240220-005','0001','2024-02-20',8.0,'Delivered');
CREATE TABLE Product (Product_ID CHAR (8) PRIMARY KEY ON CONFLICT FAIL, Product_Name CHAR (50) NOT NULL ON CONFLICT ROLLBACK, Description CHAR (255), Marked_Price Real DEFAULT 0, Category_ID INTEGER REFERENCES Category (Category_ID) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL", Quantity INTEGER DEFAULT (0));
INSERT INTO "Product" VALUES('K001','Notebook','A4 size, lined, 100 pages',5.0,1,100);
INSERT INTO "Product" VALUES('K002','Pen','Ballpoint pen, black ink',1.5,2,200);
INSERT INTO "Product" VALUES('K003','Pencil','HB pencil, 12 pack',2.0,2,50);
INSERT INTO "Product" VALUES('K004','Eraser','Rubber eraser, pink',0.5,2,150);
INSERT INTO "Product" VALUES('K005','Ruler','12-inch ruler, plastic',1.0,2,80);
INSERT INTO "Product" VALUES('K006','Glue Stick','20g glue stick',2.5,3,60);
INSERT INTO "Product" VALUES('K007','Markers','Set of 8 colored markers',5.0,3,40);
INSERT INTO "Product" VALUES('K008','Paintbrush','Round paintbrush, size 8',3.0,3,30);
INSERT INTO "Product" VALUES('K009','Paper','A4 size, white paper, 50 sheets',3.0,1,200);
INSERT INTO "Product" VALUES('K000','Scissors','Small scissors, stainless steel',4.0,2,70);
COMMIT;
