-- dbviz-04-stationery-shop
--
-- SQL source of db/dbviz-04-stationery-shop.db, generated by tools/dump-schema.py.
-- Rebuild the database with:
--     sqlite3 db/dbviz-04-stationery-shop.db < schema/dbviz-04-stationery-shop.sql
-- Then check it with:
--     python3 tools/check-db.py
--
-- Tables are written parents first, so the rows load with foreign keys
-- enforced. "PRAGMA foreign_keys" is per connection and has no effect inside a
-- transaction, which is why it is set before BEGIN: SQLite ignores it
-- otherwise, and the setting is not stored in the database file.


PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

CREATE TABLE Category (Category_ID INTEGER PRIMARY KEY ON CONFLICT FAIL, Category_Name CHAR (20) NOT NULL ON CONFLICT ROLLBACK);
INSERT INTO "Category" ("Category_ID", "Category_Name") VALUES (1, 'Notebooks');
INSERT INTO "Category" ("Category_ID", "Category_Name") VALUES (2, 'Writing Instruments');
INSERT INTO "Category" ("Category_ID", "Category_Name") VALUES (3, 'Art Supplies');

CREATE TABLE Customer (Customer_ID CHAR (4) NOT NULL PRIMARY KEY ON CONFLICT FAIL, First_Name CHAR (40), Last_Name CHAR (20) NOT NULL ON CONFLICT ROLLBACK, Email CHAR (50) NOT NULL ON CONFLICT ROLLBACK, Phone_Number CHAR (15) NOT NULL ON CONFLICT ROLLBACK, Address CHAR (200) NOT NULL ON CONFLICT ROLLBACK);
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('0001', 'John', 'Doe', 'john.doe@example.com', '3456789', '123 Main St, City');
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('0002', 'Jane', 'Smith', 'jane.smith@example.com', '9876543', '456 Oak Ave, City');
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('0003', 'Emily', 'Brown', 'emily.brown@example.com', '5555777', '789 Pine St, City');
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('1004', 'David', 'Lee', 'david.lee@example.com', '1111111', '101 Maple Dr, City');
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('1005', 'Olivia', 'Taylor', 'olivia.taylor@example.com', '2222222', '202 Birch Ln, City');
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('2106', 'Noah', 'Carter', 'noah.carter@example.com', '3333333', '303 Cedar Rd, City');
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('2207', 'Emma', 'Johnson', 'emma.johnson@example.com', '4444444', '404 Chestnut Ct, City');
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('2418', 'Liam', 'Williams', 'liam.williams@example.com', '5555555', '505 Cypress Ave, City');
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('2519', 'Ava', 'Jones', 'ava.jones@example.com', '6666666', '606 Douglas Blvd, City');
INSERT INTO "Customer" ("Customer_ID", "First_Name", "Last_Name", "Email", "Phone_Number", "Address") VALUES ('2610', 'Sophia', 'Miller', 'sophia.miller@example.com', '7777777', '707 Elm St, City');

CREATE TABLE Orders (Order_ID CHAR (8) NOT NULL PRIMARY KEY ON CONFLICT FAIL, Customer_ID CHAR (4) REFERENCES Customer (Customer_ID) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL", Order_Date DATE NOT NULL ON CONFLICT ROLLBACK, Total_Amount REAL DEFAULT 0, Status CHAR (10));
INSERT INTO "Orders" ("Order_ID", "Customer_ID", "Order_Date", "Total_Amount", "Status") VALUES ('20231001-001', '2106', '2023-10-01', 10.0, 'Shipped');
INSERT INTO "Orders" ("Order_ID", "Customer_ID", "Order_Date", "Total_Amount", "Status") VALUES ('20231115-002', '2207', '2023-11-15', 5.0, 'Delivered');
INSERT INTO "Orders" ("Order_ID", "Customer_ID", "Order_Date", "Total_Amount", "Status") VALUES ('20231225-003', '1004', '2023-12-25', 20.0, 'Pending');
INSERT INTO "Orders" ("Order_ID", "Customer_ID", "Order_Date", "Total_Amount", "Status") VALUES ('20240110-004', '0003', '2024-01-10', 15.0, 'Shipped');
INSERT INTO "Orders" ("Order_ID", "Customer_ID", "Order_Date", "Total_Amount", "Status") VALUES ('20240220-005', '0001', '2024-02-20', 8.0, 'Delivered');

CREATE TABLE Product (Product_ID CHAR (8) NOT NULL PRIMARY KEY ON CONFLICT FAIL, Product_Name CHAR (50) NOT NULL ON CONFLICT ROLLBACK, Description CHAR (255), Marked_Price Real DEFAULT 0, Category_ID INTEGER REFERENCES Category (Category_ID) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL", Quantity INTEGER DEFAULT (0));
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K001', 'Notebook', 'A4 size, lined, 100 pages', 5.0, 1, 100);
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K002', 'Pen', 'Ballpoint pen, black ink', 1.5, 2, 200);
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K003', 'Pencil', 'HB pencil, 12 pack', 2.0, 2, 50);
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K004', 'Eraser', 'Rubber eraser, pink', 0.5, 2, 150);
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K005', 'Ruler', '12-inch ruler, plastic', 1.0, 2, 80);
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K006', 'Glue Stick', '20g glue stick', 2.5, 3, 60);
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K007', 'Markers', 'Set of 8 colored markers', 5.0, 3, 40);
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K008', 'Paintbrush', 'Round paintbrush, size 8', 3.0, 3, 30);
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K009', 'Paper', 'A4 size, white paper, 50 sheets', 3.0, 1, 200);
INSERT INTO "Product" ("Product_ID", "Product_Name", "Description", "Marked_Price", "Category_ID", "Quantity") VALUES ('K000', 'Scissors', 'Small scissors, stainless steel', 4.0, 2, 70);

CREATE TABLE Order_Item (Order_Item_ID CHAR (10) NOT NULL PRIMARY KEY ON CONFLICT FAIL, Order_ID CHAR (12) REFERENCES Orders (Order_ID) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL", Product_ID CHAR (8) REFERENCES Product (Product_ID) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL", Quantity INTEGER DEFAULT 0, Selling_Price REAL);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('1', '20231001-001', 'K001', 2, 5.0);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('2', '20231001-001', 'K002', 1, 1.5);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('3', '20231115-002', 'K003', 1, 2.0);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('4', '20231115-002', 'K004', 2, 0.5);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('5', '20231225-003', 'K005', 3, 1.0);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('6', '20231225-003', 'K006', 2, 2.5);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('7', '20240110-004', 'K007', 1, 5.0);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('8', '20240110-004', 'K008', 2, 3.0);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('9', '20240220-005', 'K009', 4, 3.0);
INSERT INTO "Order_Item" ("Order_Item_ID", "Order_ID", "Product_ID", "Quantity", "Selling_Price") VALUES ('10', '20240220-005', 'K000', 1, 4.0);

COMMIT;

-- should report nothing:
PRAGMA foreign_key_check;
