-- dbviz-06-lunch-delivery
--
-- SQL source of db/dbviz-06-lunch-delivery.db, generated by tools/dump-schema.py.
-- Rebuild the database with:
--     sqlite3 db/dbviz-06-lunch-delivery.db < schema/dbviz-06-lunch-delivery.sql
-- Then check it with:
--     python3 tools/check-db.py
--
-- Tables are written parents first, so the rows load with foreign keys
-- enforced. "PRAGMA foreign_keys" is per connection and has no effect inside a
-- transaction, which is why it is set before BEGIN: SQLite ignores it
-- otherwise, and the setting is not stored in the database file.


PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

CREATE TABLE Drink (
    id   INT       PRIMARY KEY
                   NOT NULL,
    name CHAR (30) NOT NULL
);
INSERT INTO "Drink" ("id", "name") VALUES (1, 'Milk Tea');
INSERT INTO "Drink" ("id", "name") VALUES (2, 'Coffee');
INSERT INTO "Drink" ("id", "name") VALUES (3, 'Chocolate');
INSERT INTO "Drink" ("id", "name") VALUES (4, 'Lemon Tea');
INSERT INTO "Drink" ("id", "name") VALUES (5, 'Lemon Water');

CREATE TABLE MainDish (
    id   INT       PRIMARY KEY
                   NOT NULL,
    name CHAR (50) NOT NULL,
    type CHAR (10) NOT NULL
);
INSERT INTO "MainDish" ("id", "name", "type") VALUES (1, 'Fried Beef Rice', 'Rice');
INSERT INTO "MainDish" ("id", "name", "type") VALUES (2, 'Chili Pork Noodle', 'Noodle');
INSERT INTO "MainDish" ("id", "name", "type") VALUES (3, 'Spicy Seafood Noodle', 'Noodle');
INSERT INTO "MainDish" ("id", "name", "type") VALUES (4, 'Curry Chicken Rice', 'Rice');
INSERT INTO "MainDish" ("id", "name", "type") VALUES (5, 'Minced Pork Rice', 'Rice');
INSERT INTO "MainDish" ("id", "name", "type") VALUES (6, 'Sesame Chicken Salad', 'Salad');
INSERT INTO "MainDish" ("id", "name", "type") VALUES (7, 'Tomato Potato Salad', 'Salad');
INSERT INTO "MainDish" ("id", "name", "type") VALUES (8, 'Tom Yum Prawn Noodle', 'Noodle');

CREATE TABLE Member (
    id    CHAR (5)  PRIMARY KEY
                    NOT NULL,
    name  CHAR (40) NOT NULL,
    phone CHAR (7)  NOT NULL
                    UNIQUE
);
INSERT INTO "Member" ("id", "name", "phone") VALUES ('A0010', 'Peter Chan', '9853203');
INSERT INTO "Member" ("id", "name", "phone") VALUES ('B5021', 'Alice Lee', '6550329');
INSERT INTO "Member" ("id", "name", "phone") VALUES ('A1211', 'Bob Wong', '5533612');
INSERT INTO "Member" ("id", "name", "phone") VALUES ('C6580', 'Cathy Lau', '7403989');
INSERT INTO "Member" ("id", "name", "phone") VALUES ('D3002', 'Mr. Leung', '9303114');

CREATE TABLE LunchOrder (
    member_id CHAR (5) NOT NULL
                       REFERENCES Member (id),
    main_id   INT      NOT NULL
                       REFERENCES MainDish (id),
    drink_id  INT      REFERENCES Drink (id),
    orderTime DATETIME NOT NULL,
    PRIMARY KEY (
        member_id,
        orderTime
    )
);
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('A0010', 1, 1, '2026-09-14 11:52:00');
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('B5021', 3, 4, '2026-09-14 12:05:00');
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('A1211', 2, 2, '2026-09-14 12:11:00');
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('C6580', 6, 5, '2026-09-14 12:24:00');
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('B5021', 4, NULL, '2026-09-14 12:58:00');
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('A0010', 4, 2, '2026-09-15 11:47:00');
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('A1211', 8, 3, '2026-09-15 12:02:00');
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('C6580', 6, 5, '2026-09-15 12:19:00');
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('B5021', 5, 1, '2026-09-15 12:33:00');
INSERT INTO "LunchOrder" ("member_id", "main_id", "drink_id", "orderTime") VALUES ('A0010', 2, 1, '2026-09-15 12:41:00');

COMMIT;

-- should report nothing:
PRAGMA foreign_key_check;
