#!/usr/bin/env python3
"""Write the SQL source of every exercise database to schema/.

Run it from the repository root after changing a database:

    python3 tools/dump-schema.py            # every db/*.db
    python3 tools/dump-schema.py db/x.db    # just one

Each database gets schema/<name>.sql holding its complete SQL text - the
CREATE statements followed by the rows as INSERTs - so the database can be
rebuilt from it exactly:

    sqlite3 db/db4-book_loan.db < schema/db4-book_loan.sql

Keeping that file in git is what makes a schema change reviewable: a diff of
the .sql shows which constraint moved, where a diff of the .db shows nothing
but a changed binary. Regenerate it whenever the database changes, and run
tools/check-db.py before committing either.
"""

import os
import sqlite3
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_DIR = os.path.join(ROOT, 'db')
SCHEMA_DIR = os.path.join(ROOT, 'schema')

HEADER = """-- %(name)s
--
-- SQL source of db/%(file)s, generated by tools/dump-schema.py.
-- Rebuild the database with:
--     sqlite3 db/%(file)s < schema/%(stem)s.sql
-- Then check it with:
--     python3 tools/check-db.py
"""


def dump(path):
    name = os.path.basename(path)
    stem = os.path.splitext(name)[0]
    con = sqlite3.connect('file:%s?mode=ro' % path, uri=True)
    tables = [r[0] for r in con.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")]
    body = '\n'.join(con.iterdump())
    con.close()

    out = os.path.join(SCHEMA_DIR, stem + '.sql')
    os.makedirs(SCHEMA_DIR, exist_ok=True)
    with open(out, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(HEADER % {'name': stem, 'file': name, 'stem': stem})
        fh.write('\n')
        fh.write(body)
        fh.write('\n')
    print('schema/%-28s %d table(s), %d lines' % (stem + '.sql', len(tables), body.count('\n') + 1))


def main():
    targets = sys.argv[1:]
    if not targets:
        targets = [os.path.join(DB_DIR, f) for f in sorted(os.listdir(DB_DIR))
                   if f.endswith(('.db', '.sqlite', '.sqlite3'))]
    if not targets:
        print('No databases found in %s' % DB_DIR)
        return 1
    for path in targets:
        dump(path)
    return 0


if __name__ == '__main__':
    sys.exit(main())
